platform :ios, '9.0'

inhibit_all_warnings!

target "horseman" do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

#swift 4.0语法开发
use_frameworks!

pod 'Alamofire', '~> 4.5'
pod 'SwiftyJSON'
pod 'HandyJSON'
pod 'Kingfisher’
pod 'SnapKit', '~> 4.0.0'
#pod 'IQKeyboardManagerSwift', '~> 5.0'
pod 'MJRefresh'
#pod 'CryptoSwift'


#pod 'GodEye', '~> 1.0.0', :configurations => ['Debug'] #还没做适配swift4.0
pod 'UMengAnalytics-NO-IDFA’ #无IDFA版SDK（请根据需要选择其中一个）
#pod 'AlamofireObjectMapper', '~> 5.0'
#pod 'ETNavBarTransparent'

end
